name: Post-PR Workflow

on:
  workflow_run:
    workflows: ["PR Workflow"]
    types:
      - completed

#permissions:
#  actions: write

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' && github.event.workflow_run.run_attempt <= 3 }}
    steps:
      - name: Check for cancelled job file in workflow run artifacts
        id: check-artifact
        uses: actions/github-script@v7
        with:
          script: |
            const runId = context.payload.workflow_run.id;
            const attemptNumber = context.payload.workflow_run.run_attempt;
            
            const allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId,
            });
            
            const cancelledJobFileName = `cancelled-job-${runId}-${attemptNumber}`;
            const cancelledJobFile = allArtifacts.data.artifacts.find(
              artifact => artifact.name === cancelledJobFileName
            );
            
            if (cancelledJobFile) {
              core.exportVariable('IS_CANCELLED_JOB_FILE_PRESENT', 'true');
              console.log('Cancelled job file found');
            } else {
              core.exportVariable('IS_CANCELLED_JOB_FILE_PRESENT', 'false');
              console.log('Cancelled job file not found');
            }
      - name: Rerun failed jobs if cancelled job file exists
        if: ${{ env.IS_CANCELLED_JOB_FILE_PRESENT == 'true' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            await github.rest.actions.reRunWorkflowFailedJobs({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            });
            console.log('Requested rerun of all failed jobs.');
